"""Zlib-specific DifferentialConfig — ready-to-plug into Stage 5.

Wires up the C FFI signatures and AlgorithmHarness configs that differentially
test generated zlib Rust against C zlib (via zlib1.dll / libz).

Phase D usage:

    from alchemist.verifier.differential_tester import verify_workspace
    from alchemist.verifier.zlib_config import zlib_diff_config

    report = verify_workspace(output_dir, diff_config=zlib_diff_config())
    assert report.passed  # only true if ALL 4 gates pass
"""

from __future__ import annotations

from pathlib import Path

from alchemist.verifier.auto_ffi import CSignature, TypedefMap
from alchemist.verifier.differential_tester import DifferentialConfig
from alchemist.verifier.proptest_gen import AlgorithmHarness


# ---------------------------------------------------------------------------
# C zlib FFI signatures
# ---------------------------------------------------------------------------

def zlib_public_signatures() -> list[CSignature]:
    """The subset of zlib's public API we exercise in Phase D."""
    return [
        CSignature(
            name="adler32",
            return_type="uLong",
            params=[
                ("adler", "uLong"),
                ("buf", "const Bytef *"),
                ("len", "uInt"),
            ],
        ),
        CSignature(
            name="crc32",
            return_type="uLong",
            params=[
                ("crc", "uLong"),
                ("buf", "const Bytef *"),
                ("len", "uInt"),
            ],
        ),
        CSignature(
            name="compress",
            return_type="int",
            params=[
                ("dest", "Bytef *"),
                ("destLen", "uLongf *"),
                ("source", "const Bytef *"),
                ("sourceLen", "uLong"),
            ],
        ),
        CSignature(
            name="uncompress",
            return_type="int",
            params=[
                ("dest", "Bytef *"),
                ("destLen", "uLongf *"),
                ("source", "const Bytef *"),
                ("sourceLen", "uLong"),
            ],
        ),
    ]


def zlib_typedefs() -> TypedefMap:
    """Zlib uses its own typedefs (uLong, Bytef, uInt). Map them to Rust."""
    # The auto_ffi C_SCALAR_MAP already knows uLong / Bytef / uInt. Returning an
    # empty TypedefMap keeps the default behavior.
    return TypedefMap()


# ---------------------------------------------------------------------------
# AlgorithmHarnesses — differential tests generated by proptest_gen
# ---------------------------------------------------------------------------

def zlib_harnesses() -> list[AlgorithmHarness]:
    """Per-algorithm differential harnesses for the zlib translation.

    Each harness assumes:
      - The Rust translation exposes top-level fns `rust_adler32`, `rust_crc32`,
        `rust_compress`, `rust_uncompress` in a `zlib_rs` glue crate OR
        reachable under the generated crates (zlib-checksum, zlib-compression).
      - The FFI crate `c_reference` exposes `c_adler32`, `c_crc32`,
        `c_compress`, `c_uncompress` with byte-slice / Vec<u8> shapes.

    The diff_test crate that differential_tester.py synthesizes will import
    from both — so these call expressions reference symbols at the crate root
    of `c_reference` and expect companion `rust_*` helpers to be defined in
    the diff_test crate's own `lib.rs` (added below).
    """
    return [
        AlgorithmHarness(
            algorithm="adler32",
            category="checksum",
            rust_call="rust_adler32(&input)",
            c_call="c_adler32(&input)",
            cases=5000,
        ),
        AlgorithmHarness(
            algorithm="crc32",
            category="checksum",
            rust_call="rust_crc32(&input)",
            c_call="c_crc32(&input)",
            cases=5000,
        ),
        AlgorithmHarness(
            algorithm="deflate",
            category="compression",
            rust_call="rust_compress(&input)",
            c_call="c_compress(&input)",
            rust_decompress_call="rust_uncompress(&compressed, input.len() + 64)",
            c_decompress_call="c_uncompress(&compressed, input.len() + 64)",
            cases=1000,
        ),
    ]


# ---------------------------------------------------------------------------
# Glue file — put alongside the FFI crate to give harnesses their `rust_*` fns
# ---------------------------------------------------------------------------

WRAPPERS_RS = """\
//! Differential-test wrappers that bridge the generated workspace and C.
//!
//! The generated `zlib-*` crates live alongside this file in the verify tree.
//! Each `rust_*` wrapper here calls into the generated Rust and returns the
//! same shape the C wrapper returns, so proptest_gen's harnesses compare
//! apples to apples.

#![allow(dead_code)]

// Generated crates — these must be declared as path deps in Cargo.toml
// of the diff_test crate that differential_tester.py emits.
use std::os::raw::{c_int, c_uchar, c_uint, c_ulong};

// -------- C wrappers --------

extern "C" {
    pub fn adler32(adler: c_ulong, buf: *const c_uchar, len: c_uint) -> c_ulong;
    pub fn crc32(crc: c_ulong, buf: *const c_uchar, len: c_uint) -> c_ulong;
    pub fn compress(dest: *mut c_uchar, dest_len: *mut c_ulong,
                    source: *const c_uchar, source_len: c_ulong) -> c_int;
    pub fn uncompress(dest: *mut c_uchar, dest_len: *mut c_ulong,
                      source: *const c_uchar, source_len: c_ulong) -> c_int;
}

pub fn c_adler32(data: &[u8]) -> u32 {
    unsafe { adler32(1, data.as_ptr(), data.len() as c_uint) as u32 }
}

pub fn c_crc32(data: &[u8]) -> u32 {
    unsafe { crc32(0, data.as_ptr(), data.len() as c_uint) as u32 }
}

pub fn c_compress(data: &[u8]) -> Vec<u8> {
    let mut dest_len: c_ulong = (data.len() as c_ulong) + (data.len() as c_ulong) / 1000 + 12;
    let mut dest = vec![0u8; dest_len as usize];
    let rc = unsafe {
        compress(dest.as_mut_ptr(), &mut dest_len, data.as_ptr(), data.len() as c_ulong)
    };
    assert_eq!(rc, 0, "C compress failed: rc={}", rc);
    dest.truncate(dest_len as usize);
    dest
}

pub fn c_uncompress(compressed: &[u8], expected_size: usize) -> Vec<u8> {
    let mut dest_len: c_ulong = expected_size as c_ulong;
    let mut dest = vec![0u8; expected_size];
    let rc = unsafe {
        uncompress(dest.as_mut_ptr(), &mut dest_len,
                   compressed.as_ptr(), compressed.len() as c_ulong)
    };
    assert_eq!(rc, 0, "C uncompress failed: rc={}", rc);
    dest.truncate(dest_len as usize);
    dest
}

// -------- Rust side wrappers (adjust if generated API names differ) --------

pub fn rust_adler32(data: &[u8]) -> u32 {
    // Expected shape: generated zlib-checksum exposes fn adler32(seed, &[u8]) -> u32
    // or a free fn `adler32` at the crate root.
    zlib_checksum::adler32(1, data)
}

pub fn rust_crc32(data: &[u8]) -> u32 {
    zlib_checksum::crc32(0, data)
}

pub fn rust_compress(data: &[u8]) -> Vec<u8> {
    zlib_compression::compress(data).expect("rust compress failed")
}

pub fn rust_uncompress(compressed: &[u8], expected_size: usize) -> Vec<u8> {
    let _ = expected_size;
    zlib_compression::uncompress(compressed).expect("rust uncompress failed")
}
"""


# ---------------------------------------------------------------------------
# Top-level builder
# ---------------------------------------------------------------------------

def zlib_diff_config(
    c_source_dir: Path,
    *,
    include_dirs: list[Path] | None = None,
) -> DifferentialConfig:
    """Build a DifferentialConfig tailored to zlib.

    Args:
        c_source_dir: directory containing zlib's C source (*.c + *.h).
        include_dirs: additional include paths for the C DLL build.
    """
    c_sources = sorted(
        f for f in Path(c_source_dir).glob("*.c")
        if "test" not in f.name.lower()
        and "example" not in f.name.lower()
    )
    return DifferentialConfig(
        c_sources=c_sources,
        c_include_dirs=list(include_dirs or [Path(c_source_dir)]),
        c_public_signatures=zlib_public_signatures(),
        c_typedefs=zlib_typedefs(),
        c_opaque_types=set(),
        harnesses=zlib_harnesses(),
        ffi_crate_name="c_zlib_ref",
    )
